/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rainhas;

/**
 *
 * @author aevan
 */
public class tabuleiro extends javax.swing.JFrame {

    /**
     * Creates new form tabuleiro
     */
    public tabuleiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        Q1 = new javax.swing.JLabel();
        Q2 = new javax.swing.JLabel();
        Q3 = new javax.swing.JLabel();
        Q4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/rainha.png"))); // NOI18N
        jLabel6.setText("jLabel1");
        jLabel6.getAccessibleContext().setAccessibleName("Queen4");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/tabuleiro.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4 Rainhas");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 300, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jL3.setText("Label");
        getContentPane().add(jL3);
        jL3.setBounds(20, 60, 60, 30);
        jL3.getAccessibleContext().setAccessibleName("jL3");

        Q1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/rainha.png"))); // NOI18N
        Q1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Q1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Q1MouseDragged(evt);
            }
        });
        Q1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Q1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Q1MouseReleased(evt);
            }
        });
        getContentPane().add(Q1);
        Q1.setBounds(150, 40, 90, 100);
        Q1.getAccessibleContext().setAccessibleName("Q1");

        Q2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/rainha.png"))); // NOI18N
        Q2.setName(""); // NOI18N
        Q2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Q2MouseDragged(evt);
            }
        });
        getContentPane().add(Q2);
        Q2.setBounds(430, 40, 90, 100);
        Q2.getAccessibleContext().setAccessibleName("Q2");
        Q2.getAccessibleContext().setAccessibleDescription("");
        Q2.getAccessibleContext().setAccessibleParent(jLabel1);

        Q3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/rainha.png"))); // NOI18N
        Q3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Q3MouseDragged(evt);
            }
        });
        getContentPane().add(Q3);
        Q3.setBounds(150, 320, 90, 100);
        Q3.getAccessibleContext().setAccessibleName("Q3");
        Q3.getAccessibleContext().setAccessibleDescription("");
        Q3.getAccessibleContext().setAccessibleParent(jLabel1);

        Q4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/rainha.png"))); // NOI18N
        Q4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Q4MouseDragged(evt);
            }
        });
        getContentPane().add(Q4);
        Q4.setBounds(430, 320, 90, 100);
        Q4.getAccessibleContext().setAccessibleName("Q4");
        Q4.getAccessibleContext().setAccessibleDescription("");
        Q4.getAccessibleContext().setAccessibleParent(jLabel1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/tabuleiro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 50, 370, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Q1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1MouseClicked
        
    }//GEN-LAST:event_Q1MouseClicked

    private void Q1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1MouseDragged
        Q1.setLocation(Q1.getLocation().x+evt.getX()-Q1.getWidth()/2, Q1.getLocation().y+evt.getY()-Q1.getHeight()/2);
    }//GEN-LAST:event_Q1MouseDragged
 
    private void Q1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1MousePressed
        
    }//GEN-LAST:event_Q1MousePressed

    private void Q2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q2MouseDragged
        Q2.setLocation(Q2.getLocation().x+evt.getX()-Q2.getWidth()/2, Q2.getLocation().y+evt.getY()-Q2.getHeight()/2);
    }//GEN-LAST:event_Q2MouseDragged

    private void Q3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q3MouseDragged
        Q3.setLocation(Q3.getLocation().x+evt.getX()-Q3.getWidth()/2, Q3.getLocation().y+evt.getY()-Q3.getHeight()/2);
    }//GEN-LAST:event_Q3MouseDragged

    private void Q4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q4MouseDragged
        Q4.setLocation(Q4.getLocation().x+evt.getX()-Q4.getWidth()/2, Q4.getLocation().y+evt.getY()-Q4.getHeight()/2);
    }//GEN-LAST:event_Q4MouseDragged

    private void Q1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1MouseReleased
        Q1.setLocation(Q1.getX(), Q1.getY());
    }//GEN-LAST:event_Q1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabuleiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
