/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rainhas;

/**
 *
 * @author aevan
 */
public class tabuleiro extends javax.swing.JFrame {

    /**
     * Creates new form tabuleiro
     */
    public tabuleiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jL3 = new javax.swing.JLabel();
        Q3 = new javax.swing.JLabel();
        Q4 = new javax.swing.JLabel();
        Q2 = new javax.swing.JLabel();
        Q1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/rainha.png"))); // NOI18N
        jLabel6.setText("jLabel1");
        jLabel6.getAccessibleContext().setAccessibleName("Queen4");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/tabuleiro.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4 Rainhas");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 300, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jL3.setText("Label");
        getContentPane().add(jL3);
        jL3.setBounds(20, 60, 60, 30);
        jL3.getAccessibleContext().setAccessibleName("jL3");

        Q3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/rainha.png"))); // NOI18N
        Q3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Q3MouseDragged(evt);
            }
        });
        getContentPane().add(Q3);
        Q3.setBounds(20, 270, 90, 90);
        Q3.getAccessibleContext().setAccessibleName("Q3");
        Q3.getAccessibleContext().setAccessibleDescription("");

        Q4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/rainha.png"))); // NOI18N
        Q4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Q4MouseDragged(evt);
            }
        });
        getContentPane().add(Q4);
        Q4.setBounds(20, 360, 90, 90);
        Q4.getAccessibleContext().setAccessibleName("Q4");
        Q4.getAccessibleContext().setAccessibleDescription("");

        Q2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/rainha.png"))); // NOI18N
        Q2.setName(""); // NOI18N
        Q2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Q2MouseDragged(evt);
            }
        });
        getContentPane().add(Q2);
        Q2.setBounds(20, 80, 90, 90);

        Q1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rainhas/images/rainha.png"))); // NOI18N
        Q1.setName(""); // NOI18N
        Q1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Q1MouseDragged(evt);
            }
        });
        getContentPane().add(Q1);
        Q1.setBounds(20, 170, 90, 100);
        Q1.getAccessibleContext().setAccessibleName("Q2");
        Q1.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(420, 120, 90, 100);

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(240, 20, 90, 100);

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(330, 20, 90, 100);

        jPanel4.setBackground(new java.awt.Color(204, 204, 0));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(420, 20, 90, 100);

        jPanel6.setBackground(new java.awt.Color(204, 204, 0));
        getContentPane().add(jPanel6);
        jPanel6.setBounds(150, 120, 90, 100);

        jPanel7.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel7);
        jPanel7.setBounds(240, 120, 90, 100);

        jPanel8.setBackground(new java.awt.Color(204, 204, 0));
        getContentPane().add(jPanel8);
        jPanel8.setBounds(330, 120, 90, 100);

        jPanel9.setBackground(new java.awt.Color(0, 102, 51));
        jPanel9.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel9ComponentAdded(evt);
            }
        });
        getContentPane().add(jPanel9);
        jPanel9.setBounds(150, 20, 90, 100);

        jPanel10.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel10);
        jPanel10.setBounds(420, 320, 90, 100);

        jPanel11.setBackground(new java.awt.Color(204, 204, 0));
        getContentPane().add(jPanel11);
        jPanel11.setBounds(240, 220, 90, 100);

        jPanel12.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel12);
        jPanel12.setBounds(330, 220, 90, 100);

        jPanel13.setBackground(new java.awt.Color(204, 204, 0));
        getContentPane().add(jPanel13);
        jPanel13.setBounds(420, 220, 90, 100);

        jPanel14.setBackground(new java.awt.Color(204, 204, 0));
        getContentPane().add(jPanel14);
        jPanel14.setBounds(150, 320, 90, 100);

        jPanel15.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel15);
        jPanel15.setBounds(240, 320, 90, 100);

        jPanel16.setBackground(new java.awt.Color(204, 204, 0));
        getContentPane().add(jPanel16);
        jPanel16.setBounds(330, 320, 90, 100);

        jPanel17.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel17);
        jPanel17.setBounds(150, 220, 90, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Q1Position(){
        Q1.setLocation(getX(),getY());
    }
    private void Q1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1MouseDragged
        Q1.setLocation(Q1.getLocation().x+evt.getX()-Q1.getWidth()/2, Q1.getLocation().y+evt.getY()-Q1.getHeight()/2);
    }//GEN-LAST:event_Q1MouseDragged

    private void Q3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q3MouseDragged
        Q3.setLocation(Q3.getLocation().x+evt.getX()-Q3.getWidth()/2, Q3.getLocation().y+evt.getY()-Q3.getHeight()/2);
    }//GEN-LAST:event_Q3MouseDragged

    private void Q4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q4MouseDragged
        Q4.setLocation(Q4.getLocation().x+evt.getX()-Q4.getWidth()/2, Q4.getLocation().y+evt.getY()-Q4.getHeight()/2);
    }//GEN-LAST:event_Q4MouseDragged

    private void Q2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q2MouseDragged
        Q2.setLocation(Q2.getLocation().x+evt.getX()-Q2.getWidth()/2, Q2.getLocation().y+evt.getY()-Q2.getHeight()/2);
    }//GEN-LAST:event_Q2MouseDragged

    private void jPanel9ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel9ComponentAdded
        jPanel9.getLocation();
    }//GEN-LAST:event_jPanel9ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabuleiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
